//Create Maze Actions
export const CREATE_MAZE = "CREATE_MAZE";
export const CRATE_MAZE_REQUEST = "CRATE_MAZE_REQUESTexport ";
export const CREATE_MAZE_SUCCESS = "CRATE_MAZE_REQUEST";
export const CREATE_MAZE_FAILURE = "CRATE_MAZE_REQUEST";

//Get Maze Actions
export const GET_MAZE = "GET_MAZE";
export const GET_MAZE_REQUEST = "GET_MAZE_REQUEST";
export const GET_MAZE_SUCCESS = "GET_MAZE_SUCCESS";
export const GET_MAZE_FAILURE = "GET_MAZE_FAILURE";

//Move Pony
export const PONY_MOVE = "PONY_MOVE";
export const PONY_MOVE_REQUEST = "PONY_MOVE_REQUEST";
export const PONY_MOVE_SUCCESS = "PONY_MOVE_SUCCESS";
export const PONY_MOVE_FAILURE = "PONY_MOVE_FAILURE";

//MAZE VISUALIZE
export const GET_MAZE_VISUALIZE = "GET_MAZE_VISUALIZE";
export const GET_MAZE_VISUALIZE_REQUEST = "GET_MAZE_VISUALIZE_REQUEST";
export const GET_MAZE_VISUALIZE_SUCCESS = "GET_MAZE_VISUALIZE_SUCCESS";
export const GET_MAZE_VISUALIZE_FAILURE = "GET_MAZE_VISUALIZE_FAILURE";

//Maze Id
export const SET_MAZE_ID = "SET_MAZE_ID";
export const CLEAR_MAZE_ID = "CLEAR_MAZE_ID";
