//Create Maze Actions
export const CREATE_MAZE = "CREATE_MAZE";
export const CRATE_MAZE_REQUEST = "CRATE_MAZE_REQUEST";
export const CREATE_MAZE_SUCCESS = "CRATE_MAZE_REQUEST";
export const CREATE_MAZE_FAILURE = "CRATE_MAZE_REQUEST";

//Get Maze Actions
export const GET_MAZE = "GET_MAZE";
export const GET_MAZE_REQUEST = "GET_MAZE_REQUEST";
export const GET_MAZE_SUCCESS = "GET_MAZE_SUCCESS";
export const GET_MAZE_FAILURE = "GET_MAZE_FAILURE";

//Move Pony
export const PONY_MOVE = "PONY_MOVE";
export const PONY_MOVE_REQUEST = "PONY_MOVE_REQUEST";
export const PONY_MOVE_SUCCESS = "PONY_MOVE_SUCCESS";
export const PONY_MOVE_FAILURE = "PONY_MOVE_FAILURE";

//MAZE VISUALIZE
export const GET_MAZE_VISUALIZE = "GET_MAZE_VISUALIZE";
export const GET_MAZE_VISUALIZE_REQUEST = "GET_MAZE_VISUALIZE_REQUEST";
export const GET_MAZE_VISUALIZE_SUCCESS = "GET_MAZE_VISUALIZE_SUCCESS";
export const GET_MAZE_VISUALIZE_FAILURE = "GET_MAZE_VISUALIZE_FAILURE";

//pony
export const SET_PONY = "SET_PONY";
export const CLEAR_PONY = "CLEAR_PONY";
export const SET_PONY_POSITION = "SET_PONY_POSITION";
export const CLEAR_PONY_POSITON = "CLEAR_PONY_POSITON";
export const SET_PONY_NAME = "SET_PONY_NAME";

//domokun
export const SET_DOMOKUN_POSITION = "SET_DOMOKUN_POSITION";
export const CLEAR_DOMOKUN_POSITION = "CLEAR_DOMOKUN_POSITION";

//end-point
export const SET_END_POINT_POSITION = "SET_END_POINT_POSITION";
export const CLEAR_END_POINT_POSITION = "CLEAR_END_POINT_POSITION";

//Board
export const SET_BOARD = "SET_BOARD";
export const CLEAR_BOARD = "CLEAR_BOARD";

//Game State
export const SET_GAME_STATE_START = "SET_GAME_STATE_START";
export const SET_GAME_STATE_WIN = "SET_GAME_STATE_WIN";
export const SET_GAME_STATE_LOOSE = "SET_GAME_STATE_LOOSE";
export const SET_GAME_STATE_STOP = "SET_GAME_STATE_STOP";

//Create Custom Game
export const CUSTOM_GAME_SET_WIDTH = "CUSTOM_GAME_SET_WIDTH";
export const CUSTOM_GAME_SET_HEIGHT = "CUSTOM_GAME_SET_HEIGHT";
export const CUSTOM_GAME_SET_PONY_NAME = "CUSTOM_GAME_SET_PONY_NAME";
export const CUSTOM_GAME_SET = "CUSTOM_GAME_SET";
export const CLEAR_CUSTOM_GAME = "CLEAR_CUSTOM_GAME";
export const CUSTOME_GAME_SET_MAZE_ID = "CUSTOME_GAME_SET_MAZE_ID";
export const CUSTOM_GAME_CREATE = "CUSTOM_GAME_CREATE";
export const CUSTOM_GAME_CREATE_REQUEST = "CUSTOM_GAME_CREATE_REQUEST";
export const CUSTOM_GAME_CREATE_SUCCESS = "CUSTOM_GAME_CREATE_SUCCESS";
export const CUSTOM_GAME_CREATE_FAILURE = "CUSTOM_GAME_CREATE_FAILURE";

//Game Screens
export const GAME_SCREEN_SET = "GAME_SCREEN_SET";
export const GAME_SCREEN_SET_MAIN = "GAME_SCREEN_SET_MAIN";
export const GAME_SCREEN_SET_GAME = "GAME_SCREEN_SET_GAME";
export const GAME_SCREEN_SET_WIN = "GAME_SCREEN_SET_WIN";

//Walls
export const SET_WALLS = "SET_WALLS";
export const CLEAR_WALLS = "CLEAR_WALLS";
